services:
  backend:
    container_name: inventory-backend
    build:
      context: backend
      dockerfile: Dockerfile
    volumes:
      - /backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=database
      - DATABASE_PORT=3306
      - DATABASE_USER=dbnava
      - DATABASE_PASSWORD=NaVa
      - DATABASE_NAME=inventory
    depends_on:
      - database

  database:
    container_name: inventory-database
    image: mysql:latest
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inventory
      MYSQL_USER: dbnava
      MYSQL_PASSWORD: NaVa
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql